version: '3'

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    env_file:
      - .env
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --expect-workers=4 --host=http://miloszhoc.cloud

  worker:
    image: locustio/locust
    env_file:
      - .env
    depends_on:
      - master
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master  --loglevel=CRITICAL --logfile=/mnt/locust/logs.log